route:
  receiver: 'slack'
  group_by: ['alertname', 'instance', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  routes:
  - match:
      severity: critical
    receiver: 'pagerduty'
    continue: true

receivers:
- name: 'slack'
  slack_configs:
  - api_url: 'https://hooks.slack.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX'
    channel: '#alertas-wondercom'
    send_resolved: true
    title: "{{ .GroupLabels.alertname }}"
    text: "{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"

- name: 'pagerduty'
  pagerduty_configs:
  - service_key: '<chave_pagerduty>'
    description: '{{ .CommonAnnotations.summary }}'
    client: 'Prometheus'
    client_url: '{{ template "pagerduty.default.clientURL" . }}'
    details:
      firing: '{{ template "pagerduty.default.instances" .Alerts.Firing }}'
